# Generated by Django 4.2.7 on 2024-03-13 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deadstock_item',
            old_name='item_name',
            new_name='deadstock_item',
        ),
        migrations.AddField(
            model_name='deadstock_item',
            name='available',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='deadstock_item',
            name='stock',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
