openapi: 3.0.3
info:
  title: ''
  version: 0.0.0
paths:
  /api/token/:
    post:
      operationId: api_token_create
      description: |-
        Takes a set of user credentials and returns an access and refresh JSON web
        token pair to prove the authentication of those credentials.
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TokenObtainPair'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/TokenObtainPair'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/TokenObtainPair'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenObtainPair'
          description: ''
  /api/token/refresh/:
    post:
      operationId: api_token_refresh_create
      description: |-
        Takes a refresh type JSON web token and returns an access type JSON web
        token if the refresh token is valid.
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TokenRefresh'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/TokenRefresh'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/TokenRefresh'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenRefresh'
          description: ''
  /book/{item_id}/:
    post:
      operationId: book_create
      parameters:
      - in: path
        name: item_id
        schema:
          type: integer
        required: true
      tags:
      - book
      security:
      - jwtAuth: []
      responses:
        '200':
          description: No response body
  /cart/add-to-cart/{b}/:
    post:
      operationId: cart_add_to_cart_create
      parameters:
      - in: path
        name: b
        schema:
          type: integer
        required: true
      tags:
      - cart
      security:
      - jwtAuth: []
      responses:
        '200':
          description: No response body
  /cart/api/order-items/:
    post:
      operationId: cart_api_order_items_create
      tags:
      - cart
      security:
      - jwtAuth: []
      responses:
        '200':
          description: No response body
  /cart/cart-delete/{b}/:
    delete:
      operationId: cart_cart_delete_destroy
      parameters:
      - in: path
        name: b
        schema:
          type: integer
        required: true
      tags:
      - cart
      security:
      - jwtAuth: []
      - {}
      responses:
        '204':
          description: No response body
  /cart/cart-remove/{b}/:
    post:
      operationId: cart_cart_remove_create
      parameters:
      - in: path
        name: b
        schema:
          type: integer
        required: true
      tags:
      - cart
      security:
      - jwtAuth: []
      responses:
        '200':
          description: No response body
  /cart/cart-view/:
    get:
      operationId: cart_cart_view_retrieve
      tags:
      - cart
      security:
      - jwtAuth: []
      responses:
        '200':
          description: No response body
  /cart/list/:
    get:
      operationId: cart_list_retrieve
      tags:
      - cart
      security:
      - jwtAuth: []
      responses:
        '200':
          description: No response body
  /cart/view-orders/:
    get:
      operationId: cart_view_orders_retrieve
      tags:
      - cart
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /categories/:
    get:
      operationId: categories_retrieve
      tags:
      - categories
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          description: No response body
    post:
      operationId: categories_create
      tags:
      - categories
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /deadstock_items/:
    get:
      operationId: deadstock_items_retrieve
      tags:
      - deadstock_items
      security:
      - jwtAuth: []
      responses:
        '200':
          description: No response body
    post:
      operationId: deadstock_items_create
      tags:
      - deadstock_items
      security:
      - jwtAuth: []
      responses:
        '200':
          description: No response body
  /deadstock_items/{id}/:
    get:
      operationId: deadstock_items_retrieve_2
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - deadstock_items
      security:
      - jwtAuth: []
      responses:
        '200':
          description: No response body
    put:
      operationId: deadstock_items_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - deadstock_items
      security:
      - jwtAuth: []
      responses:
        '200':
          description: No response body
    delete:
      operationId: deadstock_items_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - deadstock_items
      security:
      - jwtAuth: []
      responses:
        '204':
          description: No response body
  /items/:
    get:
      operationId: items_retrieve
      tags:
      - items
      security:
      - jwtAuth: []
      responses:
        '200':
          description: No response body
    post:
      operationId: items_create
      tags:
      - items
      security:
      - jwtAuth: []
      responses:
        '200':
          description: No response body
  /itemsdetail/{id}/:
    get:
      operationId: itemsdetail_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - itemsdetail
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          description: No response body
    put:
      operationId: itemsdetail_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - itemsdetail
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          description: No response body
    delete:
      operationId: itemsdetail_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - itemsdetail
      security:
      - jwtAuth: []
      - {}
      responses:
        '204':
          description: No response body
  /schema/:
    get:
      operationId: schema_retrieve
      description: |-
        OpenApi3 schema for this API. Format can be selected via content negotiation.

        - YAML: application/vnd.oai.openapi
        - JSON: application/vnd.oai.openapi+json
      parameters:
      - in: query
        name: format
        schema:
          type: string
          enum:
          - json
          - yaml
      - in: query
        name: lang
        schema:
          type: string
          enum:
          - af
          - ar
          - ar-dz
          - ast
          - az
          - be
          - bg
          - bn
          - br
          - bs
          - ca
          - ckb
          - cs
          - cy
          - da
          - de
          - dsb
          - el
          - en
          - en-au
          - en-gb
          - eo
          - es
          - es-ar
          - es-co
          - es-mx
          - es-ni
          - es-ve
          - et
          - eu
          - fa
          - fi
          - fr
          - fy
          - ga
          - gd
          - gl
          - he
          - hi
          - hr
          - hsb
          - hu
          - hy
          - ia
          - id
          - ig
          - io
          - is
          - it
          - ja
          - ka
          - kab
          - kk
          - km
          - kn
          - ko
          - ky
          - lb
          - lt
          - lv
          - mk
          - ml
          - mn
          - mr
          - ms
          - my
          - nb
          - ne
          - nl
          - nn
          - os
          - pa
          - pl
          - pt
          - pt-br
          - ro
          - ru
          - sk
          - sl
          - sq
          - sr
          - sr-latn
          - sv
          - sw
          - ta
          - te
          - tg
          - th
          - tk
          - tr
          - tt
          - udm
          - uk
          - ur
          - uz
          - vi
          - zh-hans
          - zh-hant
      tags:
      - schema
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/vnd.oai.openapi:
              schema:
                type: object
                additionalProperties: {}
            application/yaml:
              schema:
                type: object
                additionalProperties: {}
            application/vnd.oai.openapi+json:
              schema:
                type: object
                additionalProperties: {}
            application/json:
              schema:
                type: object
                additionalProperties: {}
          description: ''
  /user/api/:
    post:
      operationId: user_api_create
      tags:
      - user
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /user/getusers/:
    get:
      operationId: user_getusers_retrieve
      tags:
      - user
      security:
      - jwtAuth: []
      responses:
        '200':
          description: No response body
  /user/userlogin/:
    get:
      operationId: user_userlogin_list
      tags:
      - user
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserLogin'
          description: ''
    post:
      operationId: user_userlogin_create
      tags:
      - user
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserLogin'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/UserLogin'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/UserLogin'
        required: true
      security:
      - jwtAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserLogin'
          description: ''
components:
  schemas:
    TokenObtainPair:
      type: object
      properties:
        username:
          type: string
          writeOnly: true
        password:
          type: string
          writeOnly: true
        access:
          type: string
          readOnly: true
        refresh:
          type: string
          readOnly: true
      required:
      - access
      - password
      - refresh
      - username
    TokenRefresh:
      type: object
      properties:
        access:
          type: string
          readOnly: true
        refresh:
          type: string
      required:
      - access
      - refresh
    UserLogin:
      type: object
      properties:
        username:
          type: string
          maxLength: 150
        password:
          type: string
          writeOnly: true
          maxLength: 128
      required:
      - password
      - username
  securitySchemes:
    jwtAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
